---
name: pycodestyle
on: [push, pull_request]
jobs:
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get -y install python3 pycodestyle
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Information
        run: |
          python3 -V
          bin/cdist -V
      - name: Run pycodestyle
        run: |
          make pep8
